Insert into `soutenance` (`id_soutenance`, `CODE_Doc`, `CIN_J`, `Titre_Travail`, `Date_Soutenance`,`Grade_J`,`Statut_J`,`Etablissement_J`) values('1','16003839','IA123456','Contribution à l\'analyse multiscalaire','2022-06-22','PA','Président','ESTBM');
Insert into `soutenance` (`id_soutenance`, `CODE_Doc`, `CIN_J`, `Titre_Travail`, `Date_Soutenance`,`Grade_J`,`Statut_J`,`Etablissement_J`) values('1','16003839','IC433566','Contribution à l\'analyse multiscalaire','2022-06-22','PES','Examinateur','ESTBM');
Insert into `soutenance` (`id_soutenance`, `CODE_Doc`, `CIN_J`, `Titre_Travail`, `Date_Soutenance`,`Grade_J`,`Statut_J`,`Etablissement_J`) values('1','16003839','IT764899','Contribution à l\'analyse multiscalaire','2022-06-22','Docteur','Directeur de thése','FPBM');

Insert into `soutenance` (`id_soutenance`, `CODE_Doc`, `CIN_J`, `Titre_Travail`, `Date_Soutenance`,`Grade_J`,`Statut_J`,`Etablissement_J`) values('2','16004098','IA123456','L\'interculturalité dans la création Romanesque','2022-06-22','PA','Président','ESTBM');
Insert into `soutenance` (`id_soutenance`, `CODE_Doc`, `CIN_J`, `Titre_Travail`, `Date_Soutenance`,`Grade_J`,`Statut_J`,`Etablissement_J`) values('2','16004098','IB678900','L\'interculturalité dans la création Romanesque','2022-06-22','PH','Rapporteur','FSTBM');
Insert into `soutenance` (`id_soutenance`, `CODE_Doc`, `CIN_J`, `Titre_Travail`, `Date_Soutenance`,`Grade_J`,`Statut_J`,`Etablissement_J`) values('2','16004098','IC433566','L\'interculturalité dans la création Romanesque','2022-06-22','PES','Examinateur','ESTBM');
Insert into `soutenance` (`id_soutenance`, `CODE_Doc`, `CIN_J`, `Titre_Travail`, `Date_Soutenance`,`Grade_J`,`Statut_J`,`Etablissement_J`) values('2','16004098','IT764899','L\'interculturalité dans la création Romanesque','2022-06-22','Docteur','Directeur de thése','FPBM');

Insert into `soutenance` (`id_soutenance`, `CODE_Doc`, `CIN_J`, `Titre_Travail`, `Date_Soutenance`,`Grade_J`,`Statut_J`,`Etablissement_J`) values('3','18003000','UI234465','La gestion des risques financiers','2022-06-22','PH','Directeur de thése','FPBM');
Insert into `soutenance` (`id_soutenance`, `CODE_Doc`, `CIN_J`, `Titre_Travail`, `Date_Soutenance`,`Grade_J`,`Statut_J`,`Etablissement_J`) values('3','18003000','OP990876','La gestion des risques financiers','2022-06-22','Docteur','Invité','FSTBM');
Insert into `soutenance` (`id_soutenance`, `CODE_Doc`, `CIN_J`, `Titre_Travail`, `Date_Soutenance`,`Grade_J`,`Statut_J`,`Etablissement_J`) values('3','18003000','LU343434','La gestion des risques financiers','2022-06-22','PA','Président','FSTBM');
Insert into `soutenance` (`id_soutenance`, `CODE_Doc`, `CIN_J`, `Titre_Travail`, `Date_Soutenance`,`Grade_J`,`Statut_J`,`Etablissement_J`) values('3','18003000','FD476776','La gestion des risques financiers','2022-06-22','PES','Directeur de thése','FPBM');

Insert into `soutenance` (`id_soutenance`, `CODE_Doc`, `CIN_J`, `Titre_Travail`, `Date_Soutenance`,`Grade_J`,`Statut_J`,`Etablissement_J`) values('4','17014408','EB776886','Financement public','2022-06-23','PA','Rapporteur','ESTBM');
Insert into `soutenance` (`id_soutenance`, `CODE_Doc`, `CIN_J`, `Titre_Travail`, `Date_Soutenance`,`Grade_J`,`Statut_J`,`Etablissement_J`) values('4','17014408','FS126578','Financement public','2022-06-23','PH','Invité','FPBM');
Insert into `soutenance` (`id_soutenance`, `CODE_Doc`, `CIN_J`, `Titre_Travail`, `Date_Soutenance`,`Grade_J`,`Statut_J`,`Etablissement_J`) values('4','17014408','LM879087','Financement public','2022-06-23','PES','Co-Directeur de thése','FSTBM');

Insert into `soutenance` (`id_soutenance`, `CODE_Doc`, `CIN_J`, `Titre_Travail`, `Date_Soutenance`,`Grade_J`,`Statut_J`,`Etablissement_J`) values('5','14345262','IA123456','La valeur des connaissances en entreprise','2022-06-24','PA','Président','ESTBM');
Insert into `soutenance` (`id_soutenance`, `CODE_Doc`, `CIN_J`, `Titre_Travail`, `Date_Soutenance`,`Grade_J`,`Statut_J`,`Etablissement_J`) values('5','14345262','IB678900','La valeur des connaissances en entreprise','2022-06-24','PH','Rapporteur','FSTBM');
Insert into `soutenance` (`id_soutenance`, `CODE_Doc`, `CIN_J`, `Titre_Travail`, `Date_Soutenance`,`Grade_J`,`Statut_J`,`Etablissement_J`) values('5','14345262','IC433566','La valeur des connaissances en entreprise','2022-06-24','PES','Examinateur','ESTBM');
Insert into `soutenance` (`id_soutenance`, `CODE_Doc`, `CIN_J`, `Titre_Travail`, `Date_Soutenance`,`Grade_J`,`Statut_J`,`Etablissement_J`) values('5','14345262','IT764899','La valeur des connaissances en entreprise','2022-06-24','Docteur','Directeur de thése','FPBM');

Insert into `soutenance` (`id_soutenance`, `CODE_Doc`, `CIN_J`, `Titre_Travail`, `Date_Soutenance`,`Grade_J`,`Statut_J`,`Etablissement_J`) values('6','15556677','UB555555','Croissance démographique','2022-06-25','PA','Invité','ESTBM');
Insert into `soutenance` (`id_soutenance`, `CODE_Doc`, `CIN_J`, `Titre_Travail`, `Date_Soutenance`,`Grade_J`,`Statut_J`,`Etablissement_J`) values('6','15556677','TU333324','Croissance démographique','2022-06-25','PA','Président','FSTBM');
Insert into `soutenance` (`id_soutenance`, `CODE_Doc`, `CIN_J`, `Titre_Travail`, `Date_Soutenance`,`Grade_J`,`Statut_J`,`Etablissement_J`) values('6','15556677','UI443567','Croissance démographique','2022-06-25','PES','Co-Directeur de thése','FPBM');
Insert into `soutenance` (`id_soutenance`, `CODE_Doc`, `CIN_J`, `Titre_Travail`, `Date_Soutenance`,`Grade_J`,`Statut_J`,`Etablissement_J`) values('6','15556677','FA128600','Croissance démographique','2022-06-25','PA','Rapporteur','ESTBM');

Insert into `soutenance` (`id_soutenance`, `CODE_Doc`, `CIN_J`, `Titre_Travail`, `Date_Soutenance`,`Grade_J`,`Statut_J`,`Etablissement_J`) values('7','11098765','UI234465','Analyse temporelle et fréquentielle d\'un système dynamique du 1er ordre','2022-06-26','PH','Directeur de thése','FPBM');
Insert into `soutenance` (`id_soutenance`, `CODE_Doc`, `CIN_J`, `Titre_Travail`, `Date_Soutenance`,`Grade_J`,`Statut_J`,`Etablissement_J`) values('7','11098765','OP990876','Analyse temporelle et fréquentielle d\'un système dynamique du 1er ordre','2022-06-26','Docteur','Rapporteur','FSTBM');
Insert into `soutenance` (`id_soutenance`, `CODE_Doc`, `CIN_J`, `Titre_Travail`, `Date_Soutenance`,`Grade_J`,`Statut_J`,`Etablissement_J`) values('7','11098765','LU343434','Analyse temporelle et fréquentielle d\'un système dynamique du 1er ordre','2022-06-26','PA','Président','FSTBM');
Insert into `soutenance` (`id_soutenance`, `CODE_Doc`, `CIN_J`, `Titre_Travail`, `Date_Soutenance`,`Grade_J`,`Statut_J`,`Etablissement_J`) values('7','11098765','FD476776','Analyse temporelle et fréquentielle d\'un système dynamique du 1er ordre','2022-06-26','PES','Directeur de thése','FPBM');

Insert into `soutenance` (`id_soutenance`, `CODE_Doc`, `CIN_J`, `Titre_Travail`, `Date_Soutenance`,`Grade_J`,`Statut_J`,`Etablissement_J`) values('8','12123445','EB776886','Qualité et sécurité des produits agroalimentaires','2022-06-27','PA','Rapporteur','ESTBM');
Insert into `soutenance` (`id_soutenance`, `CODE_Doc`, `CIN_J`, `Titre_Travail`, `Date_Soutenance`,`Grade_J`,`Statut_J`,`Etablissement_J`) values('8','12123445','FS126578','Qualité et sécurité des produits agroalimentaires','2022-06-27','PH','Président','FPBM');
Insert into `soutenance` (`id_soutenance`, `CODE_Doc`, `CIN_J`, `Titre_Travail`, `Date_Soutenance`,`Grade_J`,`Statut_J`,`Etablissement_J`) values('8','12123445','LM879087','Qualité et sécurité des produits agroalimentaires','2022-06-27','PES','Co-Directeur de thése','FSTBM');

Insert into `soutenance` (`id_soutenance`, `CODE_Doc`, `CIN_J`, `Titre_Travail`, `Date_Soutenance`,`Grade_J`,`Statut_J`,`Etablissement_J`) values('9','17435678','IA123456','Régime de change et performances économiques des pays d\'afrique','2022-06-28','PA','Président','ESTBM');
Insert into `soutenance` (`id_soutenance`, `CODE_Doc`, `CIN_J`, `Titre_Travail`, `Date_Soutenance`,`Grade_J`,`Statut_J`,`Etablissement_J`) values('9','17435678','IB678900','Régime de change et performances économiques des pays d\'afrique','2022-06-28','PH','Rapporteur','FSTBM');
Insert into `soutenance` (`id_soutenance`, `CODE_Doc`, `CIN_J`, `Titre_Travail`, `Date_Soutenance`,`Grade_J`,`Statut_J`,`Etablissement_J`) values('9','17435678','IC433566','Régime de change et performances économiques des pays d\'afrique','2022-06-28','PES','Invité','ESTBM');
Insert into `soutenance` (`id_soutenance`, `CODE_Doc`, `CIN_J`, `Titre_Travail`, `Date_Soutenance`,`Grade_J`,`Statut_J`,`Etablissement_J`) values('9','17435678','IT764899','Régime de change et performances économiques des pays d\'afrique','2022-06-28','Docteur','Directeur de thése','FPBM');

Insert into `soutenance` (`id_soutenance`, `CODE_Doc`, `CIN_J`, `Titre_Travail`, `Date_Soutenance`,`Grade_J`,`Statut_J`,`Etablissement_J`) values('10','18102299','UB555555','La simulation du réacteur Slow pake-2 par le code MCNPS','2022-06-29','PA','Co-Directeur de thése','ESTBM');
Insert into `soutenance` (`id_soutenance`, `CODE_Doc`, `CIN_J`, `Titre_Travail`, `Date_Soutenance`,`Grade_J`,`Statut_J`,`Etablissement_J`) values('10','18102299','TU333324','La simulation du réacteur Slow pake-2 par le code MCNPS','2022-06-29','PA','Président','FSTBM');
Insert into `soutenance` (`id_soutenance`, `CODE_Doc`, `CIN_J`, `Titre_Travail`, `Date_Soutenance`,`Grade_J`,`Statut_J`,`Etablissement_J`) values('10','18102299','UI443567','La simulation du réacteur Slow pake-2 par le code MCNPS','2022-06-29','PES','Co-Directeur de thése','FPBM');
Insert into `soutenance` (`id_soutenance`, `CODE_Doc`, `CIN_J`, `Titre_Travail`, `Date_Soutenance`,`Grade_J`,`Statut_J`,`Etablissement_J`) values('10','18102299','FA128600','La simulation du réacteur Slow pake-2 par le code MCNPS','2022-06-29','PA','Rapporteur','ESTBM');